dataset:
  name: "ChestXray"
  train_img: "/content/drive/MyDrive/MyModel_Segment/Final_Project/LungSegment_Compare/Data/X_train.npy"
  train_msk: "/content/drive/MyDrive/MyModel_Segment/Final_Project/LungSegment_Compare/Data/y_train.npy"
  test_img: "/content/drive/MyDrive/MyModel_Segment/Final_Project/LungSegment_Compare/Data/X_test.npy"
  test_msk: "/content/drive/MyDrive/MyModel_Segment/Final_Project/LungSegment_Compare/Data/y_test.npy"

  image_size: [256, 256]
  seed: 42

dataloader:
  train:
    batch_size: 4
    num_workers: 2
    shuffle: true
    pin_memory: true
  val:
    batch_size: 1
    num_workers: 2
    shuffle: false
    pin_memory: false
  test:
    batch_size: 1
    num_workers: 2
    shuffle: false
    pin_memory: false

augmentation:
  train:
    resize: [256, 256]
    shift_scale_rotate:
      shift_limit: 0.2
      scale_limit: 0.2
      rotate_limit: 30
      p: 0.5
    rgb_shift:
      r_shift_limit: 25
      g_shift_limit: 25
      b_shift_limit: 25
      p: 0.5
    brightness_contrast:
      brightness_limit: 0.3
      contrast_limit: 0.3
      p: 0.5
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  val:
    resize: [256, 256]
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
